### ISSUE TITLE
The system cannot find the file specified. / Windows

### ISSUE THREAD

**Issue by SebsSa** [eclipse-iofog/iofogctl#78]
Hi, guys,

i just came across the iofog project and wanted to try it out directly on windows (yes i know).
So I tried the Quick Start Guide (https://iofog.org/docs/1.3.0/getting-started/quick-start.html)

Unfortunately I get this error :

> C:\Users\xx\Desktop\xx\iofog>iofogctl version
> [38;5;117miofogctl Unified Cli
> [0m
> [38;5;117mCopyright (C) 2019, Edgeworx, Inc.
> [0m
> version: 1.3.2-dev
> platform: windows/amd64
> commit: 0ef675c0395c864ff72750a4af73959bc07ed4b3
> date: 2019-12-10T14:36:22+1300
> 
> C:\Users\xx\Desktop\xx\iofog>iofogctl deploy
> [38;5;1m✘ open : The system cannot find the file specified.[0m

and here on Git the Windows option is not mentioned at all.
Is there a solution or is Windows not supported at all?

Many greetings

**Comment by SergeRadinovich** [comment]
Hey @SebsSa, Windows is supported. You have run `iofogctl deploy` without providing the `-f` flag.

Note that the quickstart guide does things like 'echo' so you would need to run those commands in a Bash terminal in Windows. Otherwise just copy the files manually and use the `iofogctl deploy -f ...` commands while pointing to the files on your Windows filesystem.

**Comment by Pixcell** [comment]
Hi @SebsSa,

iofogctl should work properly on windows.
The error you got here is due to the fact that the `iofogctl deploy` command expects a yaml file as argument (similar to kubectl apply if you are familiar with Kubernetes)

This is the relevant section of the Quickstart:

```bash
echo "---
apiVersion: iofog.org/v1
kind: ControlPlane
metadata:
  name: ecn
spec:
  iofogUser:
    name: Quick
    surname: Start
    email: user@domain.com
    password: q1u45ic9kst563art
  controllers:
  - name: local-controller
    host: localhost
---
apiVersion: iofog.org/v1
kind: Connector
metadata:
  name: local-connector
spec:
  host: localhost
---
apiVersion: iofog.org/v1
kind: Agent
metadata:
  name: local-agent
spec:
  host: localhost" > /tmp/quick-start.yaml
iofogctl deploy -f /tmp/quick-start.yaml
```

As you can see, this creates a file `quick-start.yaml` in the tmp folder, then use `iofogctl deploy -f /tmp/quick-start.yaml` to deploy the ECN described in yaml.

You can always get more informations on the usage of iofogctl by suffixing all commands with `--help` (I.E: `iofogctl deploy --help`), as markdown files in the /docs folder of this repo, or on iofog.org: https://iofog.org/docs/1.3.0/iofogctl/usage.html

Please let us know if you encounter any other issue.

**Comment by SebsSa** [comment]
This was my bad. Thank you ;)
